stages:
  - build
  - manifest
  - sign

variables:
  COSIGN_VERSION: "v1.4.1"

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - export tag1="${CI_REGISTRY_IMAGE}/morello-pcuabi-env:latest"
  - export tag2="${CI_REGISTRY_IMAGE}/morello-pcuabi-env:nightly"

build-and-push-amd64:
  stage: build
  image: ${CI_REGISTRY}/morello/morello-ci-containers/morello-android
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker build -t $tag1.amd64 -t ${tag2}.amd64 .
    - docker push ${tag1}.amd64
    - docker push ${tag2}.amd64

build-and-push-arm64:
  stage: build
  image: ${CI_REGISTRY}/morello/morello-ci-restricted-containers/morello-morelloie:latest.arm64
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker build -t ${tag1}.arm64 -t ${tag2}.arm64 .
    - docker push ${tag1}.arm64
    - docker push ${tag2}.arm64
  tags:
    - arm64_fast

build-and-push-manifest:
  stage: manifest
  image: ${CI_REGISTRY}/morello/morello-ci-containers/morello-android
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker manifest create ${tag1} ${tag1}.amd64 ${tag1}.arm64
    - docker manifest create ${tag2} ${tag2}.amd64 ${tag2}.arm64
    - docker manifest annotate  ${tag1} ${tag1}.amd64 --os linux --arch amd64
    - docker manifest annotate  ${tag1} ${tag1}.arm64 --os linux --arch arm64
    - docker manifest annotate  ${tag2} ${tag2}.amd64 --os linux --arch amd64
    - docker manifest annotate  ${tag2} ${tag2}.arm64 --os linux --arch arm64
    - docker manifest push ${tag1}
    - docker manifest push ${tag2}

sign-images:
  stage: sign
  image: ${CI_REGISTRY}/morello/morello-ci-containers/morello-android
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - sudo wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 -O /usr/local/bin/cosign
    - sudo chmod +x /usr/local/bin/cosign
    - cosign sign --key $COSIGN_PRIVATE_KEY ${tag1}.amd64
    - cosign sign --key $COSIGN_PRIVATE_KEY ${tag2}.amd64
    - cosign sign --key $COSIGN_PRIVATE_KEY ${tag1}.arm64
    - cosign sign --key $COSIGN_PRIVATE_KEY ${tag2}.arm64
    - cosign sign --key $COSIGN_PRIVATE_KEY ${tag1}
    - cosign sign --key $COSIGN_PRIVATE_KEY ${tag2}
